version: '3.0'

services:
    mongo:
        image: mongo
        volumes:
          - mongodata:/data/db
    mqtt:
      image: ncarlier/mqtt
    sensor:
        build:
            context: .
        image: service-sensor
        env_file: docker-compose.env
        environment: 
            NODEID: "node-sensor"
            PORT: 3000
            SERVICES: sensor
        ports:
            - "3000:3000"
        depends_on:
            - mqtt
    data:
        build:
            context: .
        image: service-data
        env_file: docker-compose.env
        environment: 
            NODEID: "node-data"
            PORT: 4000
            SERVICES: data
        ports:
            - "4000:4000"
        depends_on:
            - mqtt
            - mongo
        links:
            - mongo
    analytics:
        build:
            context: .
        image: service-data
        env_file: docker-compose.env
        environment: 
            NODEID: "node-analytics"
            PORT: 5000
            SERVICES: analytics
        ports:
            - "5000:5000"
        depends_on:
            - mqtt
            - mongo
        links:
            - mongo
    siddhi:
        build:
            context: ./siddhi-docker
        image: siddhi
        ports:
            - "6000:6000"
        depends_on:
            - analytics
    gateway:
        build:
            context: .
        image: gateway
        env_file: docker-compose.env
        environment: 
            NODEID: "node-gateway"
            PORT: 4321
            SERVICES: gateway
        ports:
            - "4321:4321"
        depends_on:
            - mqtt
volumes:
    mongodata: