version: '3.0'

services:
    nats:
        image: nats:latest
    sensor:
        build:
            context: .
        image: service-sensor
        env_file: docker-compose.env
        environment: 
            NODEID: "node-sensor"
            PORT: 3000
            SERVICES: sensor
        ports:
            - "3000:3000"
        depends_on:
            - nats
    data:
        build:
            context: .
        image: service-data
        env_file: docker-compose.env
        environment: 
            NODEID: "node-data"
            PORT: 4000
            SERVICES: data
        ports:
            - "4000:4000"
        depends_on:
            - nats
